package com.uran.gamblingstation;

import com.uran.gamblingstation.matcher.ModelMatcher;
import com.uran.gamblingstation.model.Stake;

import java.time.Month;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import static java.time.LocalDateTime.of;

public class StakeTestData {

    public static final ModelMatcher<Stake> MATCHER = new ModelMatcher<>(
            (expected, actual) -> expected == actual ||
                    (Objects.equals(expected.getId(), actual.getId())
                            && Objects.equals(expected.getUser(), actual.getUser())
                            && Objects.equals(expected.getHorse(), actual.getHorse())
                            && Objects.equals(expected.getDateTime(), actual.getDateTime())
                            && Objects.equals(expected.getStakeValue(), actual.getStakeValue())
                            && Objects.equals(expected.getWins(), actual.getWins())
                    )
    );

    public static final Stake STAKE_1 = new Stake(100.25, of(2016, Month.MAY, 30, 10, 0), false);
    public static final Stake STAKE_2 = new Stake(100.25, of(2016, Month.JUNE, 12, 13, 30), false);
    public static final Stake STAKE_3 = new Stake(100.25, of(2016, Month.JUNE, 13, 19, 45), false);
    public static final Stake STAKE_4 = new Stake(100.25, of(2016, Month.JULY, 21, 9, 15), false);
    public static final Stake STAKE_5 = new Stake(100.25, of(2016, Month.AUGUST, 5, 10, 10), false);


    public static final List<Stake> STAKES = Arrays.asList(STAKE_5, STAKE_4, STAKE_3, STAKE_2, STAKE_1);
}
/*CREATE TABLE stakes
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  user_id     INTEGER NOT NULL ,
  horse_id    INTEGER NOT NULL ,
  stake_value DOUBLE NOT NULL ,
  date_time   TIMESTAMP NOT NULL ,
  wins        BOOLEAN DEFAULT FALSE ,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (horse_id) REFERENCES horses (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX stakes_unique_user_id_idx ON stakes (user_id, date_time);*/