DROP TABLE IF EXISTS stakes;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS horses;

CREATE SEQUENCE global_seq START 100000;

-----------------------------------------------------------------
CREATE TABLE horses
(
  id         INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  name       VARCHAR NOT NULL,
  ru_name    VARCHAR NOT NULL,
  age        INTEGER NOT NULL,
  wins       INTEGER NOT NULL
);
CREATE UNIQUE INDEX horses_unique_name_idx ON horses (name);
-----------------------------------------------------------------
CREATE TABLE users
(
  id         INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  password   VARCHAR(255) NOT NULL,
  registered TIMESTAMP DEFAULT now(),
  enabled    BOOL   DEFAULT TRUE
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);
-----------------------------------------------------------------
CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR ,
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
-----------------------------------------------------------------

CREATE TABLE wallets
(
  user_id     INTEGER NOT NULL,
  cash_value  DOUBLE NOT NULL,
  CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX wallets_unique_user_id_idx ON wallets (user_id);

-----------------------------------------------------------------
CREATE TABLE stakes
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  user_id     INTEGER NOT NULL ,
  horse_id    INTEGER NOT NULL ,
  stake_value DOUBLE NOT NULL ,
  date_time   TIMESTAMP DEFAULT now(),
  wins        BOOL DEFAULT FALSE ,
  amount      DOUBLE NOT NULL ,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (horse_id) REFERENCES horses (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX stakes_unique_user_id_idx ON stakes (user_id, date_time);
-----------------------------------------------------------------
